version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "${DB_CONNECTION}"
    volumes:
      - ./certs/root.crt:/certs/root.crt:ro
